runtime: python39 # or your desired runtime
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15
  target_throughput_utilization: 0.6
entrypoint: gunicorn -b :$PORT repair_order_system.wsgi
env_variables:
  DJANGO_SETTINGS_MODULE: "repair_order_system.settings"